In [1]:
import numpy as np
a=np.arange(10)

In [2]:
print(a)
a.reshape(1,10)


[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [3]:
b=a.copy()
b[8]=1
print(b,a)

[0 1 2 3 4 5 6 7 1 9] [0 1 2 3 4 5 6 7 8 9]


In [4]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
print (a.shape)

(10,)


In [7]:
res=[]

In [8]:
res.append(a[9])

In [14]:
res.append(a[8])
res.append(a[7])
res.append(10)

In [15]:
print(res)

[9, 8, 7, 8, 7, 10]


In [16]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
print(np.argmax(res))

5
