In [1]:
import numpy as np
a=np.arange(10)

In [2]:
print(a)
a.reshape(1,10)


[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [3]:
b=a.copy()
b[8]=1
print(b,a)

[0 1 2 3 4 5 6 7 1 9] [0 1 2 3 4 5 6 7 8 9]


In [4]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
print (a.shape)

(10,)


In [7]:
res=[]

In [8]:
res.append(a[9])

In [14]:
res.append(a[8])
res.append(a[7])
res.append(10)

In [15]:
print(res)

[9, 8, 7, 8, 7, 10]


In [16]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
print(np.argmax(res))

5


In [18]:
w = np.zeros((24,1))

In [19]:
print(w)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [21]:
w =np.random.randn(24,1)*0.1
print(w)

[[ 0.07948703]
 [ 0.05062868]
 [ 0.18706987]
 [-0.04986386]
 [ 0.05444951]
 [-0.05060973]
 [ 0.12266353]
 [ 0.04764227]
 [ 0.13034532]
 [-0.02822623]
 [-0.05085231]
 [ 0.04716728]
 [-0.00336016]
 [ 0.02894001]
 [ 0.00947832]
 [ 0.07908341]
 [ 0.07745213]
 [-0.10869935]
 [-0.08285293]
 [ 0.0627005 ]
 [-0.00935938]
 [-0.12704595]
 [-0.01931479]
 [-0.05574826]]
